plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown

highlighter: rouge

name: Daniel Frampton Developer Website

permalink: /blog/:year/:month/:day/:title

collections:
  guides:
    output: true
